language: cpp
dist: trusty
sudo: enabled
os: linux
branches:
  only:
  - CI
before-install:
addons:
  apt:
    update: true
install:
  - sudo apt-get install avrdude avrdude-doc avr-libc binutils-avr gcc-avr gdb-avr
  - sudo apt-get install cppcheck

#  - pip install --user --upgrade pip
# To use CPPUNIT tests in the code
#  - sudo apt-get install libcppunit-dev
# To use gcov to learn code coverage (% of code being used in a program) which is not that useful for us
#  - pip install --user cpp-coveralls
# To use cpplint without the ./ and by not having the script in the root folder
#  - pip install --user cpplint

script:
   - chmod +x ./setmode.sh && ./setmode.sh debug
   - make
#  - chmod +x ./build.sh && bash -c ./build.sh

after_success:
#     - chmod u+x ./cpplint.py
#     - ./cpplint.py --quiet --recursive ./codeCommun/tp/tp9/
     - cppcheck --enable=style --language=c++ --std=c99 ./codeCommun/tp/tp9/

notifications:
  email:
    - simon.zhang@polymtl.ca




