language: cpp
dist: trusty
sudo: enabled
os: linux
before-install:
addons:
  apt:
    update: true
install:
  - sudo apt-get install avrdude avrdude-doc avr-libc binutils-avr gcc-avr gdb-avr
  - sudo apt-get install cppcheck

#  - pip install --user --upgrade pip
# To use CPPUNIT tests in the code
#  - sudo apt-get install libcppunit-dev
# To use gcov to learn code coverage (% of code being used in a program) which is not that useful for us
#  - pip install --user cpp-coveralls
# To use cpplint without the ./ and by not having the script in the root folder
#  - pip install --user cpplint

script:
   - chmod +x ./setmode.sh && ./setmode.sh debug
   - make

after_success:
  #To use for styling checking
     # - chmod u+x ./cpplint.py
     # - ./cpplint.py --quiet --root=codeCommun/tp/tp9/ --recursive ./codeCommun/tp/tp9/
     # - clang-tidy 
  #To use for static code analysis
  #Need to include own .cfg file for our own library functions
     - cppcheck  --enable=warning,performance --language=c++ --std=c99 --platform=avr8 --library=avr.cfg ./codeCommun/tp/tp9/
    
  #Send the clang-tidy suggested changes
     # - curl --upload-file ./file https://transfer.sh/file


notifications:
  email:
    - simon.zhang@polymtl.ca




